<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Log;
use Carbon\Carbon;
use ZipArchive;

class BackupDatabase extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'backup:database 
                           {--type=database : Type of backup (database, files, full)}
                           {--keep=7 : Number of backups to keep}
                           {--notify : Send notification after backup}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create database backup and optionally clean old backups';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $type = $this->option('type');
        $keep = (int) $this->option('keep');
        $notify = $this->option('notify');

        $this->info("Starting {$type} backup...");

        try {
            // Create backup
            $backupName = 'auto_backup_' . date('Y-m-d_H-i-s');
            
            switch ($type) {
                case 'database':
                    $result = $this->createDatabaseBackup($backupName);
                    break;
                case 'files':
                    $result = $this->createFilesBackup($backupName);
                    break;
                case 'full':
                    $result = $this->createFullBackup($backupName);
                    break;
                default:
                    $this->error("Invalid backup type: {$type}");
                    return 1;
            }

            if (!$result['success']) {
                $this->error("Backup failed: " . $result['message']);
                Log::error("Automated backup failed: " . $result['message']);
                return 1;
            }

            $this->info("Backup created successfully: " . $result['backup']['filename']);
            $this->info("Size: " . $result['backup']['size']);

            // Clean old backups
            if ($keep > 0) {
                $this->cleanOldBackups($keep, $type);
            }

            Log::info("Automated backup completed: " . $result['backup']['filename']);
            
            if ($notify) {
                $this->sendBackupNotification($result['backup']);
            }

            return 0;

        } catch (\Exception $e) {
            $this->error("Backup failed: " . $e->getMessage());
            Log::error("Automated backup failed: " . $e->getMessage());
            return 1;
        }
    }

    /**
     * Create database backup
     */
    private function createDatabaseBackup($backupName)
    {
        try {
            $dbConfig = config('database.connections.' . config('database.default'));
            $backupPath = storage_path('app/backups');
            
            if (!is_dir($backupPath)) {
                mkdir($backupPath, 0755, true);
            }
            
            $filename = $backupName . '_database.sql';
            $filepath = $backupPath . '/' . $filename;

            // Get all tables
            $tables = DB::select('SHOW TABLES');
            $tableKey = 'Tables_in_' . $dbConfig['database'];

            $sql = "-- Automated Database Backup Created: " . date('Y-m-d H:i:s') . "\n";
            $sql .= "-- Database: " . $dbConfig['database'] . "\n";
            $sql .= "-- Generated by LMS Trimurti Automated Backup System\n\n";
            $sql .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";

            $this->info("Backing up " . count($tables) . " tables...");

            $bar = $this->output->createProgressBar(count($tables));
            $bar->start();

            foreach ($tables as $table) {
                $tableName = $table->$tableKey;
                
                // Get CREATE TABLE statement
                $createTable = DB::select("SHOW CREATE TABLE `$tableName`");
                $sql .= "-- Table structure for table `$tableName`\n";
                $sql .= "DROP TABLE IF EXISTS `$tableName`;\n";
                $sql .= $createTable[0]->{'Create Table'} . ";\n\n";

                // Get table data
                $rows = DB::select("SELECT * FROM `$tableName`");
                if (!empty($rows)) {
                    $sql .= "-- Dumping data for table `$tableName`\n";
                    $sql .= "LOCK TABLES `$tableName` WRITE;\n";
                    
                    foreach ($rows as $row) {
                        $values = array_values((array)$row);
                        $values = array_map(function($value) {
                            return $value === null ? 'NULL' : "'" . addslashes($value) . "'";
                        }, $values);
                        
                        $sql .= "INSERT INTO `$tableName` VALUES (" . implode(',', $values) . ");\n";
                    }
                    
                    $sql .= "UNLOCK TABLES;\n\n";
                }
                
                $bar->advance();
            }

            $sql .= "SET FOREIGN_KEY_CHECKS = 1;\n";

            file_put_contents($filepath, $sql);
            $bar->finish();
            $this->newLine();

            return [
                'success' => true,
                'backup' => [
                    'filename' => $filename,
                    'path' => $filepath,
                    'size' => $this->formatBytes(filesize($filepath)),
                    'type' => 'database'
                ]
            ];
        } catch (\Exception $e) {
            return [
                'success' => false,
                'message' => $e->getMessage()
            ];
        }
    }

    /**
     * Create files backup
     */
    private function createFilesBackup($backupName)
    {
        try {
            $backupPath = storage_path('app/backups');
            $filename = $backupName . '_files.zip';
            $filepath = $backupPath . '/' . $filename;

            $zip = new ZipArchive();
            if ($zip->open($filepath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
                throw new \Exception('Cannot create ZIP file');
            }

            $this->info("Backing up files...");

            // Add storage files
            if (is_dir(storage_path('app/public'))) {
                $this->addDirectoryToZip($zip, storage_path('app/public'), 'storage/');
            }
            
            // Add uploads if exists
            if (is_dir(public_path('uploads'))) {
                $this->addDirectoryToZip($zip, public_path('uploads'), 'uploads/');
            }

            $zip->close();

            return [
                'success' => true,
                'backup' => [
                    'filename' => $filename,
                    'path' => $filepath,
                    'size' => $this->formatBytes(filesize($filepath)),
                    'type' => 'files'
                ]
            ];
        } catch (\Exception $e) {
            return [
                'success' => false,
                'message' => $e->getMessage()
            ];
        }
    }

    /**
     * Create full backup
     */
    private function createFullBackup($backupName)
    {
        try {
            // Create database backup
            $dbBackup = $this->createDatabaseBackup($backupName . '_db');
            if (!$dbBackup['success']) {
                throw new \Exception('Failed to create database backup');
            }

            // Create files backup
            $filesBackup = $this->createFilesBackup($backupName . '_files');
            if (!$filesBackup['success']) {
                throw new \Exception('Failed to create files backup');
            }

            // Create combined ZIP
            $backupPath = storage_path('app/backups');
            $filename = $backupName . '_full.zip';
            $filepath = $backupPath . '/' . $filename;

            $zip = new ZipArchive();
            if ($zip->open($filepath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
                throw new \Exception('Cannot create combined ZIP file');
            }

            // Add database backup to ZIP
            $zip->addFile($dbBackup['backup']['path'], 'database/' . $dbBackup['backup']['filename']);
            
            // Add files backup to ZIP
            $zip->addFile($filesBackup['backup']['path'], 'files/' . $filesBackup['backup']['filename']);

            $zip->close();

            // Remove temporary files
            unlink($dbBackup['backup']['path']);
            unlink($filesBackup['backup']['path']);

            return [
                'success' => true,
                'backup' => [
                    'filename' => $filename,
                    'path' => $filepath,
                    'size' => $this->formatBytes(filesize($filepath)),
                    'type' => 'full'
                ]
            ];
        } catch (\Exception $e) {
            return [
                'success' => false,
                'message' => $e->getMessage()
            ];
        }
    }

    /**
     * Add directory to ZIP archive recursively
     */
    private function addDirectoryToZip($zip, $dir, $zipPath = '')
    {
        if (is_dir($dir)) {
            $files = scandir($dir);
            foreach ($files as $file) {
                if ($file != '.' && $file != '..') {
                    $fullPath = $dir . '/' . $file;
                    $relativePath = $zipPath . $file;
                    
                    if (is_dir($fullPath)) {
                        $zip->addEmptyDir($relativePath);
                        $this->addDirectoryToZip($zip, $fullPath, $relativePath . '/');
                    } else {
                        $zip->addFile($fullPath, $relativePath);
                    }
                }
            }
        }
    }

    /**
     * Clean old backup files
     */
    private function cleanOldBackups($keep, $type)
    {
        $backupPath = storage_path('app/backups');
        $files = glob($backupPath . '/auto_backup_*_' . $type . '.*');
        
        // Sort files by modification time (newest first)
        usort($files, function($a, $b) {
            return filemtime($b) - filemtime($a);
        });

        // Keep only the specified number of backups
        $toDelete = array_slice($files, $keep);
        $deleted = 0;

        foreach ($toDelete as $file) {
            if (unlink($file)) {
                $deleted++;
            }
        }

        if ($deleted > 0) {
            $this->info("Cleaned {$deleted} old backup(s)");
        }
    }

    /**
     * Format bytes to human readable format
     */
    private function formatBytes($bytes, $precision = 2)
    {
        $units = array('B', 'KB', 'MB', 'GB', 'TB');
        
        for ($i = 0; $bytes > 1024; $i++) {
            $bytes /= 1024;
        }
        
        return round($bytes, $precision) . ' ' . $units[$i];
    }

    /**
     * Send backup notification (placeholder)
     */
    private function sendBackupNotification($backup)
    {
        // This is a placeholder for notification functionality
        // You can implement email notifications here
        $this->info("Notification: Backup completed - " . $backup['filename']);
        Log::info("Backup notification sent for: " . $backup['filename']);
    }
}